
server:
  port: 10002
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j1902n?charaterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
mybatis:
  type-aliases-package: com.qf.j1902.pojo
  mapper-locations: mapping/*.xml
myname: dubitian 
